name: Docker Container CI

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: asdf-vm/actions/install@v1.1.0
      - run: |
          hadolint Dockerfile
          pnpx prettier --check .
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.0.1
      - uses: docker/setup-buildx-action@v1.1.1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/vyas-n/devcontainer:local
          outputs: type=docker,dest=/tmp/devcontainer.tar
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: devcontainer
          path: /tmp/devcontainer.tar
  synk-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          name: devcontainer
          path: /tmp
      - run: |
          docker load --input /tmp/devcontainer.tar
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/vyas-n/devcontainer:local
          args: --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
  anchore-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          name: devcontainer
          path: /tmp
      - run: |
          docker load --input /tmp/devcontainer.tar
      - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
        uses: anchore/scan-action@main
        with:
          image: ghcr.io/vyas-n/devcontainer:local
          fail-build: false
          acs-report-enable: true
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.0.1
      - uses: docker/setup-buildx-action@v1.1.1
      - uses: actions/download-artifact@v2
        with:
          name: devcontainer
          path: /tmp
      - run: |
          docker load --input /tmp/devcontainer.tar
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: vyas-n
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: ghcr.io/vyas-n/devcontainer # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          file: Dockerfile
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
